### ISSUE TITLE
require-dir is broken and cannot get "/api/users"

### ISSUE THREAD

**Issue by jtmorrisbytes** [uhray/crud#3]
currently I am using windows 10 on nodejs version 8.2.1 and express 4.15.5

I dont know if I am doing this wrong, but i followed your simple example from the npm page https://www.npmjs.com/package/node-crud and am having two problems:
1. require-dir is broken at file .\index.js line 93:
 if( !require.extensions.hasOwnPropterty(ext))

when using a suggested fix to change it to
(if !Object.prototype.hasOwnProperty.call(require.extensions,ext))

and using your simple example:
------------------file: index.js --------------
var crud = require('node-crud'),
express = require('express'),
app = express();

// set up some express middleware 
app.use(require('body-parser').urlencoded({ extended: true }));
app.use(require('body-parser').json());

// Let's create our first Crud API route 
crud.entity('/users').Read()
.use(function(req, res, next) {
// express middleware capability 
next();
})
.pipe(function(data, query, cb) {
cb(null, [ { name: 'bobby tables' } ]);
});

crud.launch(app);

app.listen(3000);
--------------------------------------------------------
express says cannot get "/api/users/"

there are no other errors or messages thrown by this so i dont know whats going on but wanted to let you know that this  seems broken on node 8

**Comment by rthomps7** [comment]
@jjmo18 

1. For the `require-dir` issue, this a package we do not manage [here](https://github.com/aseemk/requireDir). Perhaps it's broken. All our active stuff us using node v7.5.0, and I will not have any time soon to address this. Feel free to submit a pull request using something other than `require-dir`, or submit a pull request to them to fix their issue.
2. Try hitting `/api/users` instead of `/api/users/`

**Comment by nevercast** [comment]
2. Correct. On Windows path.join creates backslashes not forward slashes. I'll make a PR to fix this.

**Comment by nevercast** [comment]
Made said PR. https://github.com/uhray/crud/pull/4

**Comment by rthomps7** [comment]
#4

**Comment by nevercast** [comment]
Note: I've tested require-dir@0.3.2 (latest at time of comment) and it seems to operate fine. If there are any bugs present in the version of require-dir node-crud is using, updating is an option. (Currently node-crud uses require-dir@0.1.0).
