### ISSUE TITLE
Contributing and Testing notes missing.

### ISSUE THREAD

**Issue by nevercast** [uhray/crud#5]
Hello,

I've been working on a PR for a feature, but there is no documentation on running tests/coverage or the contributing procedure. (Formatting/Style). I see you have used a linter so hopefully that's sufficient for code style.

Information on running tests would be appreciated. I should note that I've mocha installed globally and ran `mocha` to receive an error

```
D:\Source\Repos\crud\dist\crud.js:418
})(window);
   ^

ReferenceError: window is not defined
```

It should be noted that I then tried with jsdom registered (I have this installed globally). _This fixes it_, of course. But there is no mention of jsdom in your gulpfile. My concern is if my testing method is different to yours my tests are not valid.

Kind regards,
Josh.

**Comment by nevercast** [comment]
With tests working, they do not pass on the upstream. If you can confirm that they don't pass on your end either I'm more than happy to PR a fix.

**Comment by rthomps7** [comment]
@nevercast -

Sorry about this. I've pushed a fix to everything [here](https://github.com/uhray/crud/commit/ed72605378bb4f311bbe42797a12379c031a1494).
